### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by TeunVR** [minvws/nl-covid19-notification-app-design#10]
Het vrijgeven van de source-code van de covid-notification app is belangrijk voor de acceptatie ervan.
Het is echter niet eenvoudig om te verifiëren dat de binary die in de App Store en Play Store staat ook werkelijk op basis van die source-code is gebouwd.

Andere projecten (bv Signal en Telegram) staan voor dezelfde uitdaging: 
https://github.com/signalapp/Signal-iOS/issues/641
https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios

Helaas lijkt er niet direct een technische oplossing hiervoor te zijn. 
Misschien is het een idee om dit procesmatig in te regelen. 
Bv door onafhankelijke “getuigen” tijdens bouwen/submitten naar stores?

**Comment by bwbroersma** [comment]
This is not the correct repo for this issue, this is about the visual design only.
The code repo is yet to be published, there is a requirements folder in [nl-covid19-notification-app-coordination](https://github.com/minvws/nl-covid19-notification-app-coordination) so that repo would better fix this discussion (BTW I agree and there should be more stuff to take care of, e.g. anonymous posting and decoy submissions, some of [we advised](https://openstate.eu/wp-content/uploads/sites/14/2020/04/Vraag-en-antwoordformulier-VWS.pdf) long ago).

**Comment by TeunVR** [comment]
Can you transfer this issue to the other repo? I don’t have write-permissions.

**Comment by bwbroersma** [comment]
I've zero rights, I'm a technical critic just like you, not a member of the development team.

**Comment by TeunVR** [comment]
Ok i’ll close this one. Copied to other repo.

**Comment by pro-sumer** [comment]
> This is not the correct repo for this issue, this is about the visual design only.

Is it?

The single line description indeed uses the word “design”, but it’s not clear whether that means UI/UX (look & feel) or code architecture (internal structure).

Maybe @jelleprins can clarify that to manage expectations?

**Comment by bwbroersma** [comment]
It is, also see the recent [architecture](https://github.com/minvws/nl-covid19-notification-app-coordination/tree/master/architecture) addition to the [`nl-covid19-notification-app-coordination`](https://github.com/minvws/nl-covid19-notification-app-coordination) repo. I do agree it can and should be clearly stated by adding **visual** design, because I was wondering at first too.

**Comment by pro-sumer** [comment]
I was not aware of that repo...

Thank you for mentioning it!
